import { Users } from './../interface/users';
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class UsersService {
  arrayUsers: Users[] = [
    {
      id: 1,
      firstName: 'OVERALL = 99',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 2,
      firstName: 'OVERALL = 98',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 3,
      firstName: 'OVERALL = 97',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 4,
      firstName: 'OVERALL = 96',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 5,
      firstName: 'OVERALL = 95',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 6,
      firstName: 'OVERALL = 94',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 7,
      firstName: 'OVERALL = 93',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 8,
      firstName: 'OVERALL = 92',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 9,
      firstName: 'OVERALL = 91',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 10,
      firstName: 'OVERALL = 90',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 11,
      firstName: 'OVERALL = 89',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 12,
      firstName: 'OVERALL = 88',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 13,
      firstName: 'OVERALL = 87',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 14,
      firstName: 'OVERALL = 86',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 15,
      firstName: 'OVERALL = 85',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 16,
      firstName: 'OVERALL = 84',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 17,
      firstName: 'OVERALL = 83',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 18,
      firstName: 'OVERALL = 82',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 19,
      firstName: 'OVERALL = 81',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 20,
      firstName: 'OVERALL = 80',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 21,
      firstName: 'OVERALL = 79',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 22,
      firstName: 'OVERALL = 78',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 23,
      firstName: 'OVERALL = 77',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 24,
      firstName: 'OVERALL = 76',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 25,
      firstName: 'OVERALL = 75',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 26,
      firstName: 'OVERALL = 74',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 27,
      firstName: 'OVERALL = 73',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 28,
      firstName: 'OVERALL = 72',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 29,
      firstName: 'OVERALL = 71',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 30,
      firstName: 'OVERALL = 70',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 31,
      firstName: 'OVERALL = 69',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 32,
      firstName: 'OVERALL = 68',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 33,
      firstName: 'OVERALL = 67',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 34,
      firstName: 'OVERALL = 66',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 35,
      firstName: 'OVERALL = 65',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 36,
      firstName: 'OVERALL = 64',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 37,
      firstName: 'OVERALL = 63',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 38,
      firstName: 'OVERALL = 62',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 39,
      firstName: 'OVERALL = 61',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
    {
      id: 40,
      firstName: 'OVERALL = 60',
      lastName: '',
      email: '',
      image: '',
      title: '',
    },
  ];

  constructor() {}
  getAllUsers() {
    return this.arrayUsers;
  }

  getNameUsers() {
    return this.getAllUsers().filter((u) => u.firstName);
  }
}
