import { Injectable } from '@angular/core';
import { Roster, Wrestler } from '../interface/wrestler.inteface';

@Injectable({
  providedIn: 'root',
})
export class WrestlerService {
  wrestlers: Wrestler[] = [
    {
      id: 1,
      name: 'ROMAN',
      lastname: 'REIGNS',
      stats_total: 99,
      roster: Roster.SMACKDOWN,
    },
    {
      id: 2,
      name: 'THE',
      lastname: 'ROCK',
      stats_total: 98,
      roster: Roster.RAW,
    },
    {
      id: 3,
      name: 'STONE COLD',
      lastname: 'STEVE AUSTIN',
      stats_total: 97,
      roster: Roster.SMACKDOWN,
    },
    {
      id: 4,
      name: 'THE',
      lastname: 'UNDERTAKER',
      stats_total: 96,
      roster: Roster.RAW,
    },
    {
      id: 5,
      name: 'JOHN',
      lastname: 'CENA',
      stats_total: 95,
      roster: Roster.SMACKDOWN,
    },
    {
      id: 6,
      name: 'HULK',
      lastname: 'HOGAN',
      stats_total: 94,
      roster: Roster.RAW,
    },
    {
      id: 7,
      name: 'SETH',
      lastname: 'ROLLINS',
      stats_total: 93,
      roster: Roster.SMACKDOWN,
    },
    {
      id: 8,
      name: 'BRET',
      lastname: 'HART',
      stats_total: 92,
      roster: Roster.RAW,
    },
    {
      id: 9,
      name: 'CODY',
      lastname: 'RHODES',
      stats_total: 91,
      roster: Roster.SMACKDOWN,
    },
    {
      id: 10,
      name: 'SHAWN',
      lastname: 'MICHAELS',
      stats_total: 90,
      roster: Roster.RAW,
    },
    {
      id: 11,
      name: 'THE FIEND',
      lastname: 'BRAY WYATT',
      stats_total: 89,
      roster: Roster.SMACKDOWN,
    },
    {
      id: 12,
      name: 'ULTIMATE',
      lastname: 'WARRIOR',
      stats_total: 88,
      roster: Roster.RAW,
    },
    {
      id: 13,
      name: 'BRUNO',
      lastname: 'SAMMARTINO',
      stats_total: 87,
      roster: Roster.SMACKDOWN,
    },
    {
      id: 14,
      name: 'TIGER',
      lastname: 'MASK',
      stats_total: 86,
      roster: Roster.RAW,
    },
    {
      id: 15,
      name: 'TRIPLE',
      lastname: 'H',
      stats_total: 85,
      roster: Roster.SMACKDOWN,
    },
    {
      id: 16,
      name: 'ANDRE',
      lastname: 'THE GIANT',
      stats_total: 84,
      roster: Roster.RAW,
    },
    {
      id: 17,
      name: 'RANDY',
      lastname: 'ORTON',
      stats_total: 83,
      roster: Roster.SMACKDOWN,
    },
    {
      id: 18,
      name: 'YOKOZUNA',
      lastname: '',
      stats_total: 82,
      roster: Roster.RAW,
    },
    {
      id: 19,
      name: 'LOGAN',
      lastname: 'PAUL',
      stats_total: 81,
      roster: Roster.SMACKDOWN,
    },
    {
      id: 20,
      name: 'MAIN EVENT',
      lastname: 'JEY USO',
      stats_total: 80,
      roster: Roster.RAW,
    },
    {
      id: 21,
      name: 'GUNTHER',
      lastname: '',
      stats_total: 79,
      roster: Roster.SMACKDOWN,
    },
    {
      id: 22,
      name: 'EDDIE',
      lastname: 'GUERRERO',
      stats_total: 78,
      roster: Roster.RAW,
    },
    {
      id: 23,
      name: 'ROB',
      lastname: 'VAN DAM',
      stats_total: 77,
      roster: Roster.SMACKDOWN,
    },
    {
      id: 24,
      name: 'CM',
      lastname: 'PUNK',
      stats_total: 76,
      roster: Roster.RAW,
    },
    {
      id: 25,
      name: 'BATISTA',
      lastname: '',
      stats_total: 75,
      roster: Roster.SMACKDOWN,
    },
    {
      id: 26,
      name: 'DREW',
      lastname: 'MCINTYRE',
      stats_total: 74,
      roster: Roster.RAW,
    },
    {
      id: 27,
      name: 'KURT',
      lastname: 'ANGLE',
      stats_total: 73,
      roster: Roster.SMACKDOWN,
    },
    {
      id: 28,
      name: 'MACHO MAN',
      lastname: 'RANDY SAVAGE',
      stats_total: 72,
      roster: Roster.RAW,
    },
    {
      id: 29,
      name: 'REY',
      lastname: 'MYSTERIO',
      stats_total: 71,
      roster: Roster.SMACKDOWN,
    },
    {
      id: 30,
      name: 'LA',
      lastname: 'KNIGHT',
      stats_total: 70,
      roster: Roster.RAW,
    },
    {
      id: 31,
      name: 'SAMI',
      lastname: 'ZAYN',
      stats_total: 69,
      roster: Roster.SMACKDOWN,
    },
    {
      id: 32,
      name: 'FINN',
      lastname: 'BALOR',
      stats_total: 68,
      roster: Roster.RAW,
    },
    {
      id: 33,
      name: 'DAMIAN',
      lastname: 'PRIEST',
      stats_total: 67,
      roster: Roster.SMACKDOWN,
    },
    {
      id: 34,
      name: 'KEVIN',
      lastname: 'OWENS',
      stats_total: 66,
      roster: Roster.RAW,
    },
    {
      id: 35,
      name: 'KANE',
      lastname: '',
      stats_total: 65,
      roster: Roster.SMACKDOWN,
    },
    {
      id: 36,
      name: 'SPIDER',
      lastname: 'MAN',
      stats_total: 64,
      roster: Roster.RAW,
    },
    {
      id: 37,
      name: 'AJ',
      lastname: 'STYLES',
      stats_total: 63,
      roster: Roster.SMACKDOWN,
    },
    {
      id: 38,
      name: 'BOOKER',
      lastname: 'T',
      stats_total: 62,
      roster: Roster.RAW,
    },
    {
      id: 39,
      name: 'RICOCHET',
      lastname: '',
      stats_total: 61,
      roster: Roster.SMACKDOWN,
    },
    {
      id: 40,
      name: 'YELLOW',
      lastname: 'DEVIL',
      stats_total: 60,
      roster: Roster.RAW,
    },
  ];
  constructor() {}

  getWrestlers(roster?: Roster) {
    if (roster)
      return this.wrestlers.filter((wrestler) => wrestler.roster === roster);

    return this.wrestlers;
  }
}
